name: gtb_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.7"

dependencies:
  flutter:
    sdk: flutter

  gtb_core:
    git:
      url: https://github.com/smiqueias/gtb_digital
      ref: dev
      path: modules/gtb_core


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
