name: gtb_digital

packages:
  - modules/*

command:
  bootstrap:
    runPubGetInParallel: true

    environment:
      sdk: ^3.8.1
      flutter: ">=3.32.7"

scripts:

  pub_get:
    description: Get all packages/modules
    run: flutter pub get

  pub_upgrade:
    description: Upgrade all packages/modules
    run: flutter pub upgrade

  clean:
    description: Clean all packages/modules
    run: flutter clean