name: gtb_digital

packages:
  - modules/*

command:
  bootstrap:
    runPubGetInParallel: true

    environment:
      sdk: ^3.8.1
      flutter: ">=3.32.7"

scripts:
  pub_get:
    description: Get packages from pub.dev
    run: flutter pub get