name: gtb_home
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0
  flutter: ^3.38.6

dependencies:
  flutter:
    sdk: flutter
  gtb_core:
    git:
      url: https://github.com/smiqueias/gtb_digital
      ref: dev
      path: modules/gtb_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  gtb_analysis_options:
    git:
      url: https://github.com/smiqueias/gtb_digital
      ref: dev
      path: modules/gtb_analysis_options

flutter: