name: gtb_teatro
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0
  flutter: ^3.38.6

dependencies:
  flutter:
    sdk: flutter

  gap: ^3.0.1
  intersperse: ^2.0.0
  shimmer: ^3.0.0
  prototype_constrained_box: 2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  gtb_analysis_options:
    git:
      url: https://github.com/smiqueias/gtb_digital
      ref: dev
      path: modules/gtb_analysis_options
